# Numpy

- NumPy is a general-purpose array-processing package.
- Numpy was created to work with multidmensional arrays.
- It is the fundamental package for scientific computing with Python.
- It is open-source library.

# Why Use NumPy?
- In Python we have lists that serve the purpose of arrays, but they are slow to process.

- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

- The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

- Arrays are very frequently used in data science, where speed and resources are very important.

In [2]:
#Importing necessary library
!pip install numpy

import numpy as np 

In [5]:
#Array Creation

a = np.array(10)
type(a)

numpy.ndarray

In [ ]:
#Zero dimensional array

In [7]:
z = np.array(10)

z.ndim

0

In [ ]:
#One dimensional array

In [9]:
o = np.array([10,12,12,15])
o.ndim

1

In [ ]:
#Two dimensional array

In [10]:
t = np.array([[10,10,12,14,15]])
t.ndim

2

In [ ]:
#Three dimensional array

In [11]:
th = np.array([[[10,12,14,15,16]]])

In [12]:
th.ndim

3

In [ ]:
#Change the data type of the array elements.

In [15]:
a = np.array([10,15,52,54])

In [16]:
a.dtype

dtype('int32')

In [21]:
a = np.array([10,15,52,54], dtype = 'float')
print(a.dtype)
print('hello')
a

float64
hello


array([10., 15., 52., 54.])

# Other ways of creating an array
1. arange
2. linspace
3. zeros
4. ones
5. random

In [25]:
a = np.arange(1, 21, 2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [27]:
b = np.linspace(1,5,15, retstep=True)
b

(array([1.        , 1.28571429, 1.57142857, 1.85714286, 2.14285714,
        2.42857143, 2.71428571, 3.        , 3.28571429, 3.57142857,
        3.85714286, 4.14285714, 4.42857143, 4.71428571, 5.        ]),
 0.2857142857142857)

In [29]:
z = np.zeros([2,2])
z

array([[0., 0.],
       [0., 0.]])

In [30]:
o = np.ones([5,5])

In [31]:
o

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
r = np.random.rand(5,5)
r

array([[0.6057294 , 0.8043542 , 0.37853978, 0.27433185, 0.6850481 ],
       [0.33581904, 0.03779656, 0.54643696, 0.91952847, 0.12853788],
       [0.24706396, 0.59101776, 0.11368983, 0.25893676, 0.92311465],
       [0.76307906, 0.27715711, 0.41845894, 0.81172607, 0.41473397],
       [0.86638174, 0.69622015, 0.92798996, 0.34124088, 0.28769809]])

In [37]:
r = np.random.randint(5, size = 10)
r

array([0, 0, 1, 2, 2, 3, 1, 0, 2, 1])

# Slicing and Indexing of arrays

In [38]:
a = np.array([[1,2,3],[4,5,6]])

In [39]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
a[0,0]

1

In [41]:
a[1,2]

6

In [48]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
a[0,1:]

array([2, 3])

In [43]:
a[0:,1:]

array([[2, 3],
       [5, 6]])

In [44]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
#1 and 6
a[[0,1],[0,2]]

array([1, 6])

In [47]:
#3 and 4

a[[0,1],[2,0]]

array([3, 4])

# Reshaping the arrays 

In [49]:
a = np.random.rand(5,2)

In [50]:
a

array([[0.57491324, 0.67660342],
       [0.19094759, 0.90785905],
       [0.57091154, 0.27179587],
       [0.58828599, 0.44915594],
       [0.20740153, 0.12124909]])

In [53]:
a.reshape(2,5)

array([[0.57491324, 0.67660342, 0.19094759, 0.90785905, 0.57091154],
       [0.27179587, 0.58828599, 0.44915594, 0.20740153, 0.12124909]])

In [54]:
a.reshape(10,1)

array([[0.57491324],
       [0.67660342],
       [0.19094759],
       [0.90785905],
       [0.57091154],
       [0.27179587],
       [0.58828599],
       [0.44915594],
       [0.20740153],
       [0.12124909]])

In [56]:
a.reshape(1,10)

array([[0.57491324, 0.67660342, 0.19094759, 0.90785905, 0.57091154,
        0.27179587, 0.58828599, 0.44915594, 0.20740153, 0.12124909]])

In [57]:
a.reshape(5,-1)

array([[0.57491324, 0.67660342],
       [0.19094759, 0.90785905],
       [0.57091154, 0.27179587],
       [0.58828599, 0.44915594],
       [0.20740153, 0.12124909]])

# Aggregate Functions

- The Python numpy aggregate functions are sum, min, max, mean, average, product, median, standard deviation, variance,  percentile, and corrcoef.

In [60]:
a.min()

0.12124909445357712

In [61]:
a.std()

0.23995356743233057

In [62]:
a.var()

0.05757771452350201

In [63]:
a.mean()

0.45591232696002243

# Stacking 
- Stacking is used to join 2 different arrays.
- Vertical stacking
- Horizontal stacking

In [64]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,8,7])

In [66]:
np.hstack([a,b])

array([1, 2, 3, 4, 5, 4, 5, 6, 8, 7])

In [68]:
np.vstack([a,b])

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 8, 7]])